# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(choices=[('kwh', 'Kilowatt hour'), ('m3', 'Cubic meter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('value_increment', models.FloatField()),
                ('value_total', models.FloatField(db_index=True)),
                ('power_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='logger.Meter')),
            ],
            options={
                'db_table': 'reading',
            },
        ),
    ]
