# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kwh', 'Kilowatt hour'), ('m3', 'Cubic meter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('value_increment', models.FloatField()),
                ('value_total', models.FloatField(db_index=True)),
                ('power_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.PowerMeter')),
            ],
            options={
                'db_table': 'reading',
            },
            managers=[
                ('reports', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='ElectricityDeliveredReading',
        ),
        migrations.DeleteModel(
            name='ElectricityUsedReading',
        ),
        migrations.DeleteModel(
            name='GasReading',
        ),
    ]
