# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='tariff',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
