# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20160731_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='power_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='logger.PowerMeter'),
        ),
    ]
