# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20160915_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeterGroup',
            new_name='Meter',
        ),
        migrations.RenameField(
            model_name='meterprice',
            old_name='meter',
            new_name='meter_tariff',
        ),
    ]
