# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20160915_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='meter',
            new_name='meter_tariff',
        ),
        migrations.AlterIndexTogether(
            name='reading',
            index_together=set([('meter_tariff', 'datetime')]),
        ),
    ]
