# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0006_auto_20160915_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeterPrice',
            new_name='MeterTariffPrice',
        ),
        migrations.RemoveField(
            model_name='metertariff',
            name='slug',
        ),
        migrations.AlterField(
            model_name='metertariff',
            name='tariff',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
