# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0008_auto_20160915_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metertariff',
            old_name='meter_group',
            new_name='meter',
        ),
    ]
