# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0010_auto_20160915_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_actual', to='logger.Meter')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.AlterIndexTogether(
            name='electricityactual',
            index_together=set([('meter', 'datetime')]),
        ),
    ]
