# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0011_auto_20160916_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricityActual',
            new_name='EnergyActual',
        ),
    ]
