# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0012_auto_20160917_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyactual',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_actual', to='logger.Meter'),
        ),
    ]
