# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0013_auto_20160917_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='ReadingTotal',
        ),
    ]
