# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0014_auto_20170314_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyActual',
            new_name='ReadingActual',
        ),
    ]
