# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0015_auto_20170314_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingactual',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings_actual', to='logger.Meter'),
        ),
        migrations.AlterField(
            model_name='readingtotal',
            name='meter_tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings_total', to='logger.MeterTariff'),
        ),
    ]
